"""Init

Revision ID: 8be3438e24e1
Revises: 2302c649badc
Create Date: 2023-08-02 16:47:20.081987

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8be3438e24e1'
down_revision = '2302c649badc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=150), nullable=False),
                    sa.Column('email', sa.String(length=250), nullable=False),
                    sa.Column('number', sa.String(length=150), nullable=False),
                    sa.Column('bd_date', sa.Date(), nullable=False),
                    sa.Column('additional_data', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_index(op.f('ix_users_bd_date'), 'users', ['bd_date'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_number'), 'users', ['number'], unique=True)
    op.drop_index('ix_todos_title', table_name='todos')
    op.drop_table('todos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
                    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='todos_pkey')
                    )
    op.create_index('ix_todos_title', 'todos', ['title'], unique=False)
    op.drop_index(op.f('ix_users_number'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_bd_date'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
