"""Init

Revision ID: c7e20ad1fb86
Revises: 4f328286677e
Create Date: 2023-08-02 18:40:48.028672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e20ad1fb86'
down_revision = '4f328286677e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('surname', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('number', sa.String(length=150), nullable=False),
    sa.Column('bd_date', sa.Date(), nullable=False),
    sa.Column('additional_data', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_contacts_bd_date'), 'contacts', ['bd_date'], unique=False)
    op.create_index(op.f('ix_contacts_name'), 'contacts', ['name'], unique=False)
    op.create_index(op.f('ix_contacts_number'), 'contacts', ['number'], unique=True)
    op.create_index(op.f('ix_contacts_surname'), 'contacts', ['surname'], unique=False)
    op.drop_index('ix_users_bd_date', table_name='users')
    op.drop_index('ix_users_name', table_name='users')
    op.drop_index('ix_users_number', table_name='users')
    op.drop_index('ix_users_surname', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('number', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('bd_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('additional_data', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.create_index('ix_users_surname', 'users', ['surname'], unique=False)
    op.create_index('ix_users_number', 'users', ['number'], unique=False)
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.create_index('ix_users_bd_date', 'users', ['bd_date'], unique=False)
    op.drop_index(op.f('ix_contacts_surname'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_number'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_bd_date'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
